---
- hosts: all
  become: true
  tasks:
    - name: install apache2, add php support for apache package and update repository index
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes