---
- name: Plabook to remove Apache and Php
  hosts: all
  become: true
  tasks:
   - name: Update repository index
     ansible.builtin.apt:
      update_cache: true

   - name: Remove apache2 package
     ansible.builtin.apt:
      name: apache2
      state: absent

   - name: Remove support for php
     ansible.builtin.apt:
      name: libapache2-mod-php
      state: absent
